version: '3.2'
services:
  
  datos:
    container_name: py_sp
    build:
      context: ./rellenar
      dockerfile: Dockerfile
    depends_on:
      - db
    restart: on-failure
    volumes:
      - type: bind
        source: ./rellenar
        target: /usr/src/app
  db:
    image: mongo
    container_name: mongo_compose
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: s123
  
  debms:
    image: mongo-express
    container_name: mexpress_compose
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: examen
      ME_CONFIG_BASICAUTH_PASSWORD: a123
      ME_CONFIG_MONGODB_SERVER: mongo_compose
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: s123
  
  api:
    container_name: py_app
    build:
      context: ./tabla
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 5000:5000
    restart: on-failure
    volumes:
      - type: bind
        source: ./tabla
        target: /usr/src/app
